# Generated by Django 4.1.5 on 2023-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_categorytranslation_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestranslation',
            name='short_desc',
            field=models.TextField(default=1, verbose_name='Short Desc'),
            preserve_default=False,
        ),
    ]
