# Generated by Django 4.1.5 on 2023-01-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_servicestranslation_short_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='ServicesTranslation',
            new_name='ServiceTranslation',
        ),
        migrations.AlterModelOptions(
            name='servicetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'service Translation'},
        ),
        migrations.AlterModelTable(
            name='servicetranslation',
            table='landing_service_translation',
        ),
    ]
