# Generated by Django 4.1.5 on 2023-01-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_rename_services_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
