# Generated by Django 4.1.5 on 2023-01-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_faq_faqtranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
