# Generated by Django 4.1.5 on 2023-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_region_district_client_regiontranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='F.I.O'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientTranslation',
        ),
    ]
